### PR TITLE
remove playground

### PR DESCRIPTION
**Pull request by cnryb**
remove playground, use weex-playground/android instead

### CODE REVIEW

**Comment by cnryb** [comment]
@YorkShen How is this project released?

**Comment by YorkShen** [comment]
As this project is not part of Apache Weex officially, there is no rule nor procedure about how to release it.

And the JCenter Key is in this hosted on [SVN of ASF](https://svn.apache.org/repos/private/pmc/incubator/weex/JCenter_key.md).

**Comment by YorkShen** [comment]
@cnryb 

If there is someone able to maintain this project, I am OK with persuding VPs in Alibaba to donated it to ASF. Otherwise, we might better keep its current status.

FYI: If you need admin priviledge of this repo, I could assign it to you.

**Review by YorkShen — COMMENTED** [review]
Do you test it locally? Will it run as expected?

As hundrends of files deleted, I can't review one by one.

**Comment by cnryb** [comment]
This pr deletes the playground and appframework folders, and appframework is not referenced elsewhere.
I am now trying to make iOS devtool work in our project, Then Android.
It would be better if I could manipulate these two libraries directly.

**Comment by YorkShen** [comment]
@cnryb I will merge your PR first.

As for the problem of how should we handle Android-Devtools/iOS-Devtools, maybe you could discuss it in the mailing list. There are some legal, code maintaining and trademark issues we will meet if we choose having it donated. 

So please discuss it in the mailing list, I will explain the detail situation there.

**Pull request merged**
